; inherits: sql

; Oracle/PL-SQL keywords
[
  (keyword_connect)
  (keyword_national)
  (keyword_operator)
  (keyword_binding)
  (keyword_prior)
  (keyword_nocycle)
  (keyword_siblings)
  (keyword_forall)
  (keyword_indices)
  (keyword_rowtype)
  (keyword_save)
  (keyword_target)
  (keyword_exceptions)
  (keyword_elsif)
  (keyword_exit)
  (keyword_reverse)
  (keyword_continue)
  (keyword_loop)
  (keyword_declare)
  (keyword_atomic)
] @keyword

; Locking, MODEL, ALTER SYSTEM/SESSION, DIRECTORY, ANALYZE (#101, #107, #108, #111)
[
  (keyword_skip)
  (keyword_locked)
  (keyword_model)
  (keyword_nav)
  (keyword_keep)
  (keyword_updated)
  (keyword_dimension)
  (keyword_measures)
  (keyword_rules)
  (keyword_upsert)
  (keyword_sequential)
  (keyword_automatic)
  (keyword_iterate)
  (keyword_system)
  (keyword_scope)
  (keyword_sid)
  (keyword_memory)
  (keyword_spfile)
  (keyword_flush)
  (keyword_kill)
  (keyword_checkpoint)
  (keyword_switch)
  (keyword_logfile)
  (keyword_archive)
  (keyword_log)
  (keyword_directory)
  (keyword_compute)
  (keyword_estimate)
  (keyword_validate)
  (keyword_structure)
  (keyword_sample)
  (keyword_statistics)
] @keyword

; EXPLAIN prefix (non-ANSI; re-added over the strict ANSI base)
[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword
