; GENERATED by scripts/bundle-highlights.js - do not edit.
;
; Standalone highlights query for oracle: base -> oracle,
; with every pattern the oracle grammar cannot compile removed. Edit the
; queries/highlights.scm files listed below, then rerun the script.

; ── queries/highlights.scm ──────────────────────────────────────────────────

(object_reference
  name: (identifier) @type)

(invocation
  (object_reference
    name: (identifier) @function.call))

[
  (keyword_array)
] @function.call

(relation
  alias: (identifier) @variable)

(field
  name: (identifier) @field)

(term
  alias: (identifier) @variable)

((term
   value: (cast
    name: (keyword_cast) @function.call
    parameter: [(literal)]?)))

(literal) @string

(comment) @comment @spell

(marginalia) @comment

((literal) @number
   (#match? @number "^[-+]?%d+$"))

((literal) @float
  (#match? @float "^[-+]?%d*\.%d*$"))

(parameter) @parameter

[
  (keyword_true)
  (keyword_false)
] @boolean

[
  (keyword_asc)
  (keyword_desc)
  (keyword_nulls)
  (keyword_last)
  (keyword_default)
  (keyword_collate)
  (keyword_concurrently)
  (keyword_always)
  (keyword_generated)
  (keyword_preceding)
  (keyword_following)
  (keyword_first)
  (keyword_current_timestamp)
  (keyword_immutable)
  (keyword_atomic)
  (keyword_parallel)
  (keyword_leakproof)
  (keyword_safe)
  (keyword_cost)
  (keyword_strict)
] @attribute

[
  (keyword_materialized)
  (keyword_recursive)
  (keyword_temp)
  (keyword_temporary)
  (keyword_unlogged)
  (keyword_external)
  (keyword_volatile)
] @storageclass

[
  (keyword_case)
  (keyword_when)
  (keyword_then)
  (keyword_else)
] @conditional

[
  (keyword_select)
  (keyword_from)
  (keyword_where)
  (keyword_index)
  (keyword_join)
  (keyword_primary)
  (keyword_delete)
  (keyword_create)
  (keyword_insert)
  (keyword_merge)
  (keyword_distinct)
  (keyword_replace)
  (keyword_update)
  (keyword_into)
  (keyword_matched)
  (keyword_values)
  (keyword_value)
  (keyword_attribute)
  (keyword_set)
] @keyword

[
  (keyword_left)
  (keyword_right)
  (keyword_outer)
  (keyword_inner)
  (keyword_full)
] @keyword

[
  (keyword_order)
  (keyword_partition)
  (keyword_group)
  (keyword_rollup)
  (keyword_cube)
  (keyword_grouping)
  (keyword_sets)
  (keyword_with)
  (keyword_without)
  (keyword_as)
  (keyword_having)
  (keyword_limit)
  (keyword_offset)
  (keyword_fetch)
  (keyword_declare)
  (keyword_cursor)
  (keyword_next)
  (keyword_within)
  (keyword_leading)
  (keyword_trailing)
  (keyword_trim)
  (keyword_both)
] @keyword

[
  (keyword_table)
  (keyword_tables)
  (keyword_key)
  (keyword_references)
  (keyword_usage)
  (keyword_grant)
  (keyword_revoke)
  (keyword_privileges)
  (keyword_public)
  (keyword_foreign)
  (keyword_constraint)
  (keyword_force)
  (keyword_for)
  (keyword_if)
  (keyword_exists)
  (keyword_column)
  (keyword_cross)
  (keyword_lateral)
  (keyword_natural)
  (keyword_alter)
  (keyword_drop)
  (keyword_add)
  (keyword_view)
  (keyword_end)
  (keyword_is)
  (keyword_using)
  (keyword_between)
  (keyword_window)
  (keyword_no)
  (keyword_data)
  (keyword_type)
  (keyword_rename)
  (keyword_refresh)
  (keyword_to)
  (keyword_schema)
  (keyword_owner)
  (keyword_authorization)
] @keyword

[
  (keyword_all)
  (keyword_any)
  (keyword_some)
  (keyword_only)
  (keyword_like)
  (keyword_escape)
  (keyword_rlike)
  (keyword_similar)
  (keyword_over)
  (keyword_change)
  (keyword_modify)
  (keyword_after)
  (keyword_before)
] @keyword

[
  (keyword_range)
  (keyword_rows)
  (keyword_groups)
  (keyword_exclude)
  (keyword_current)
  (keyword_ties)
  (keyword_others)
] @keyword

[
  (keyword_row)
  (keyword_comment)
  (keyword_truncate)
  (keyword_cache)
] @keyword

[
  (keyword_language)
  (keyword_called)
  (keyword_filter)
  (keyword_function)
  (keyword_input)
  (keyword_precision)
  (keyword_restricted)
  (keyword_return)
  (keyword_returns)
  (keyword_separator)
  (keyword_setof)
  (keyword_stable)
  (keyword_support)
  (keyword_trigger)
  (keyword_unsafe)
] @keyword

[
  (keyword_admin)
  (keyword_connection)
  (keyword_cycle)
  (keyword_database)
  (keyword_encrypted)
  (keyword_increment)
  (keyword_logged)
  (keyword_none)
  (keyword_owned)
  (keyword_password)
  (keyword_reset)
  (keyword_role)
  (keyword_sequence)
  (keyword_start)
  (keyword_restart)
  (keyword_tablespace)
  (keyword_until)
  (keyword_user)
  (keyword_valid)
  (keyword_action)
  (keyword_definer)
  (keyword_invoker)
  (keyword_enable)
  (keyword_disable)
  (keyword_security)
] @keyword

[
  (keyword_out)
  (keyword_inout)
  (keyword_variadic)
  (keyword_ordinality)
] @keyword

[
  (keyword_begin)
  (keyword_commit)
  (keyword_rollback)
  (keyword_transaction)
  (keyword_savepoint)
  (keyword_release)
  (keyword_work)
  (keyword_session)
  (keyword_isolation)
  (keyword_level)
  (keyword_serializable)
  (keyword_repeatable)
  (keyword_read)
  (keyword_write)
  (keyword_committed)
  (keyword_uncommitted)
  (keyword_deferrable)
  (keyword_zone)
  (keyword_immediate)
  (keyword_deferred)
  (keyword_constraints)
  (keyword_snapshot)
  (keyword_characteristics)
] @keyword

[
  (keyword_each)
  (keyword_instead)
  (keyword_of)
  (keyword_new)
  (keyword_execute)
] @keyword

[
  (keyword_procedure)
  (keyword_percent)
  (keyword_tablesample)
  (keyword_bernoulli)
  (keyword_system)
] @keyword

[
  (keyword_restrict)
  (keyword_unbounded)
  (keyword_unique)
  (keyword_cascade)
  (keyword_check)
  (keyword_option)
  (keyword_local)
  (keyword_cascaded)
  (keyword_wait)
  (keyword_nowait)
  (keyword_maxvalue)
  (keyword_minvalue)
] @type.qualifier

[
  (keyword_int)
  (keyword_null)
  (keyword_boolean)
  (keyword_binary)
  (keyword_varbinary)
  (keyword_bit)
  (keyword_smallint)
  (keyword_bigint)
  (keyword_decimal)
  (keyword_float)
  (keyword_double)
  (keyword_numeric)
  (keyword_real)
  (double)
  (keyword_char)
  (keyword_nchar)
  (keyword_varchar)
  (keyword_nvarchar)
  (keyword_varying)
  (keyword_string)
  (keyword_json)
  (keyword_xml)
  (keyword_enum)
  (keyword_date)
  (keyword_time)
  (keyword_timestamp)
  (keyword_interval)
] @type.builtin

[
  (keyword_in)
  (keyword_and)
  (keyword_or)
  (keyword_not)
  (keyword_by)
  (keyword_on)
  (keyword_union)
  (keyword_except)
  (keyword_intersect)
] @keyword.operator

[
  "+"
  "-"
  "*"
  "/"
  "%"
  "^"
  "="
  "<"
  "<="
  "!="
  ">="
  ">"
  "<>"
  (op_other)
  (op_unary_other)
] @operator

[
  "("
  ")"
] @punctuation.bracket

[
  ";"
  ","
  "."
] @punctuation.delimiter

; ── oracle/queries/highlights.scm ───────────────────────────────────────────

[
  (keyword_connect)
  (keyword_national)
  (keyword_operator)
  (keyword_binding)
  (keyword_prior)
  (keyword_nocycle)
  (keyword_siblings)
  (keyword_forall)
  (keyword_indices)
  (keyword_rowtype)
  (keyword_save)
  (keyword_target)
  (keyword_exceptions)
  (keyword_elsif)
  (keyword_exit)
  (keyword_reverse)
  (keyword_continue)
  (keyword_loop)
  (keyword_declare)
  (keyword_atomic)
] @keyword

[
  (keyword_skip)
  (keyword_locked)
  (keyword_model)
  (keyword_nav)
  (keyword_keep)
  (keyword_updated)
  (keyword_dimension)
  (keyword_measures)
  (keyword_rules)
  (keyword_upsert)
  (keyword_sequential)
  (keyword_automatic)
  (keyword_iterate)
  (keyword_system)
  (keyword_scope)
  (keyword_sid)
  (keyword_memory)
  (keyword_spfile)
  (keyword_flush)
  (keyword_kill)
  (keyword_checkpoint)
  (keyword_switch)
  (keyword_logfile)
  (keyword_archive)
  (keyword_log)
  (keyword_directory)
  (keyword_compute)
  (keyword_estimate)
  (keyword_validate)
  (keyword_structure)
  (keyword_sample)
  (keyword_statistics)
] @keyword

[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

[
  (keyword_associate)
  (keyword_at)
  (keyword_audit)
  (keyword_authenticated)
  (keyword_authid)
  (keyword_body)
  (keyword_build)
  (keyword_bulk)
  (keyword_byte)
  (keyword_call)
  (keyword_character)
  (keyword_close)
  (keyword_cluster)
  (keyword_coalesce)
  (keyword_collect)
  (keyword_columns)
  (keyword_compile)
  (keyword_complete)
  (keyword_consider)
  (keyword_context)
  (keyword_day)
  (keyword_define)
  (keyword_demand)
  (keyword_dense_rank)
  (keyword_disassociate)
  (keyword_editionable)
  (keyword_exception)
  (keyword_exchange)
  (keyword_excluding)
  (keyword_exclusive)
  (keyword_extension)
  (keyword_fast)
  (keyword_flashback)
  (keyword_fresh)
  (keyword_hash)
  (keyword_heap)
  (keyword_identified)
  (keyword_ignore)
  (keyword_include)
  (keyword_including)
  (keyword_initrans)
  (keyword_less)
  (keyword_link)
  (keyword_list)
  (keyword_lock)
  (keyword_logging)
  (keyword_master)
  (keyword_match)
  (keyword_match_recognize)
  (keyword_mode)
  (keyword_monitoring)
  (keyword_month)
  (keyword_never)
  (keyword_noaudit)
  (keyword_nocache)
  (keyword_nologging)
  (keyword_noneditionable)
  (keyword_noparallel)
  (keyword_noreverse)
  (keyword_one)
  (keyword_online)
  (keyword_open)
  (keyword_organization)
  (keyword_package)
  (keyword_partitions)
  (keyword_passing)
  (keyword_past)
  (keyword_path)
  (keyword_pattern)
  (keyword_pctfree)
  (keyword_pctused)
  (keyword_per)
  (keyword_pipe)
  (keyword_pivot)
  (keyword_plan)
  (keyword_point)
  (keyword_policy)
  (keyword_pragma)
  (keyword_prebuilt)
  (keyword_pruning)
  (keyword_purge)
  (keyword_query)
  (keyword_rebuild)
  (keyword_restore)
  (keyword_returning)
  (keyword_reuse)
  (keyword_rewrite)
  (keyword_scn)
  (keyword_second)
  (keyword_segment)
  (keyword_selectivity)
  (keyword_share)
  (keyword_shared)
  (keyword_size)
  (keyword_source)
  (keyword_split)
  (keyword_storage)
  (keyword_subpartition)
  (keyword_subpartitions)
  (keyword_successful)
  (keyword_synonym)
  (keyword_than)
  (keyword_unpivot)
  (keyword_unusable)
  (keyword_whenever)
  (keyword_while)
  (keyword_year)
  (keyword_zonemap)
] @keyword

[
  (keyword_bfile)
  (keyword_binary_double)
  (keyword_binary_float)
  (keyword_blob)
  (keyword_clob)
  (keyword_long)
  (keyword_nclob)
  (keyword_number)
  (keyword_nvarchar2)
  (keyword_raw)
  (keyword_rowid)
  (keyword_urowid)
  (keyword_varchar2)
] @type.builtin

[
  (keyword_current_user)
  (keyword_json_table)
  (keyword_xmltable)
] @function.builtin
