; inherits: sql

; Oracle/PL-SQL keywords
[
  (keyword_connect)
  (keyword_national)
  (keyword_operator)
  (keyword_binding)
  (keyword_prior)
  (keyword_nocycle)
  (keyword_siblings)
  (keyword_forall)
  (keyword_indices)
  (keyword_rowtype)
  (keyword_save)
  (keyword_target)
  (keyword_exceptions)
  (keyword_elsif)
  (keyword_exit)
  (keyword_reverse)
  (keyword_continue)
  (keyword_loop)
  (keyword_declare)
  (keyword_atomic)
] @keyword

; Locking, MODEL, ALTER SYSTEM/SESSION, DIRECTORY, ANALYZE (#101, #107, #108, #111)
[
  (keyword_skip)
  (keyword_locked)
  (keyword_model)
  (keyword_nav)
  (keyword_keep)
  (keyword_updated)
  (keyword_dimension)
  (keyword_measures)
  (keyword_rules)
  (keyword_upsert)
  (keyword_sequential)
  (keyword_automatic)
  (keyword_iterate)
  (keyword_system)
  (keyword_scope)
  (keyword_sid)
  (keyword_memory)
  (keyword_spfile)
  (keyword_flush)
  (keyword_kill)
  (keyword_checkpoint)
  (keyword_switch)
  (keyword_logfile)
  (keyword_archive)
  (keyword_log)
  (keyword_directory)
  (keyword_compute)
  (keyword_estimate)
  (keyword_validate)
  (keyword_structure)
  (keyword_sample)
  (keyword_statistics)
] @keyword

; EXPLAIN prefix (non-ANSI; re-added over the strict ANSI base)
[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

; ============================================================
; Remaining oracle keywords
; ============================================================

[
  (keyword_associate)
  (keyword_at)
  (keyword_audit)
  (keyword_authenticated)
  (keyword_authid)
  (keyword_body)
  (keyword_build)
  (keyword_bulk)
  (keyword_byte)
  (keyword_call)
  (keyword_character)
  (keyword_close)
  (keyword_cluster)
  (keyword_coalesce)
  (keyword_collect)
  (keyword_columns)
  (keyword_compile)
  (keyword_complete)
  (keyword_consider)
  (keyword_context)
  (keyword_day)
  (keyword_define)
  (keyword_demand)
  (keyword_dense_rank)
  (keyword_disassociate)
  (keyword_editionable)
  (keyword_exception)
  (keyword_exchange)
  (keyword_excluding)
  (keyword_exclusive)
  (keyword_extension)
  (keyword_fast)
  (keyword_flashback)
  (keyword_fresh)
  (keyword_hash)
  (keyword_heap)
  (keyword_identified)
  (keyword_ignore)
  (keyword_include)
  (keyword_including)
  (keyword_initrans)
  (keyword_less)
  (keyword_link)
  (keyword_list)
  (keyword_lock)
  (keyword_logging)
  (keyword_master)
  (keyword_match)
  (keyword_match_recognize)
  (keyword_mode)
  (keyword_monitoring)
  (keyword_month)
  (keyword_never)
  (keyword_noaudit)
  (keyword_nocache)
  (keyword_nologging)
  (keyword_noneditionable)
  (keyword_noparallel)
  (keyword_noreverse)
  (keyword_one)
  (keyword_online)
  (keyword_open)
  (keyword_organization)
  (keyword_package)
  (keyword_partitions)
  (keyword_passing)
  (keyword_past)
  (keyword_path)
  (keyword_pattern)
  (keyword_pctfree)
  (keyword_pctused)
  (keyword_per)
  (keyword_pipe)
  (keyword_pivot)
  (keyword_plan)
  (keyword_point)
  (keyword_policy)
  (keyword_pragma)
  (keyword_prebuilt)
  (keyword_pruning)
  (keyword_purge)
  (keyword_query)
  (keyword_rebuild)
  (keyword_restore)
  (keyword_returning)
  (keyword_reuse)
  (keyword_rewrite)
  (keyword_scn)
  (keyword_second)
  (keyword_segment)
  (keyword_selectivity)
  (keyword_share)
  (keyword_shared)
  (keyword_size)
  (keyword_source)
  (keyword_split)
  (keyword_storage)
  (keyword_subpartition)
  (keyword_subpartitions)
  (keyword_successful)
  (keyword_synonym)
  (keyword_than)
  (keyword_unpivot)
  (keyword_unusable)
  (keyword_whenever)
  (keyword_while)
  (keyword_year)
  (keyword_zonemap)
] @keyword

[
  (keyword_bfile)
  (keyword_binary_double)
  (keyword_binary_float)
  (keyword_blob)
  (keyword_clob)
  (keyword_long)
  (keyword_nclob)
  (keyword_number)
  (keyword_nvarchar2)
  (keyword_raw)
  (keyword_rowid)
  (keyword_urowid)
  (keyword_varchar2)
] @type.builtin

[
  (keyword_current_user)
  (keyword_json_table)
  (keyword_xmltable)
] @function.builtin
