; GENERATED by scripts/bundle-highlights.js - do not edit.
;
; Standalone highlights query for bigquery: base -> bigquery,
; with every pattern the bigquery grammar cannot compile removed. Edit the
; queries/highlights.scm files listed below, then rerun the script.

; ── queries/highlights.scm ──────────────────────────────────────────────────

(object_reference
  name: (identifier) @type)

(invocation
  (object_reference
    name: (identifier) @function.call))

[
  (keyword_array)
] @function.call

(relation
  alias: (identifier) @variable)

(field
  name: (identifier) @field)

(term
  alias: (identifier) @variable)

((term
   value: (cast
    name: (keyword_cast) @function.call
    parameter: [(literal)]?)))

(literal) @string

(comment) @comment @spell

(marginalia) @comment

((literal) @number
   (#match? @number "^[-+]?%d+$"))

((literal) @float
  (#match? @float "^[-+]?%d*\.%d*$"))

(parameter) @parameter

[
  (keyword_true)
  (keyword_false)
] @boolean

[
  (keyword_asc)
  (keyword_desc)
  (keyword_nulls)
  (keyword_last)
  (keyword_default)
  (keyword_collate)
  (keyword_concurrently)
  (keyword_always)
  (keyword_generated)
  (keyword_preceding)
  (keyword_following)
  (keyword_first)
  (keyword_current_timestamp)
  (keyword_atomic)
  (keyword_parallel)
  (keyword_safe)
] @attribute

[
  (keyword_materialized)
  (keyword_recursive)
  (keyword_temp)
  (keyword_temporary)
  (keyword_unlogged)
  (keyword_external)
] @storageclass

[
  (keyword_case)
  (keyword_when)
  (keyword_then)
  (keyword_else)
] @conditional

[
  (keyword_select)
  (keyword_from)
  (keyword_where)
  (keyword_index)
  (keyword_join)
  (keyword_primary)
  (keyword_delete)
  (keyword_create)
  (keyword_insert)
  (keyword_merge)
  (keyword_distinct)
  (keyword_replace)
  (keyword_update)
  (keyword_into)
  (keyword_matched)
  (keyword_values)
  (keyword_value)
  (keyword_attribute)
  (keyword_set)
] @keyword

[
  (keyword_left)
  (keyword_right)
  (keyword_outer)
  (keyword_inner)
  (keyword_full)
] @keyword

[
  (keyword_order)
  (keyword_partition)
  (keyword_group)
  (keyword_rollup)
  (keyword_cube)
  (keyword_grouping)
  (keyword_sets)
  (keyword_with)
  (keyword_without)
  (keyword_as)
  (keyword_having)
  (keyword_limit)
  (keyword_offset)
  (keyword_declare)
  (keyword_within)
] @keyword

[
  (keyword_table)
  (keyword_tables)
  (keyword_key)
  (keyword_references)
  (keyword_usage)
  (keyword_grant)
  (keyword_revoke)
  (keyword_privileges)
  (keyword_public)
  (keyword_foreign)
  (keyword_constraint)
  (keyword_force)
  (keyword_for)
  (keyword_if)
  (keyword_exists)
  (keyword_column)
  (keyword_cross)
  (keyword_lateral)
  (keyword_natural)
  (keyword_alter)
  (keyword_drop)
  (keyword_add)
  (keyword_view)
  (keyword_end)
  (keyword_is)
  (keyword_using)
  (keyword_between)
  (keyword_window)
  (keyword_no)
  (keyword_data)
  (keyword_type)
  (keyword_rename)
  (keyword_refresh)
  (keyword_to)
  (keyword_schema)
  (keyword_owner)
] @keyword

[
  (keyword_all)
  (keyword_any)
  (keyword_some)
  (keyword_only)
  (keyword_like)
  (keyword_escape)
  (keyword_rlike)
  (keyword_similar)
  (keyword_over)
  (keyword_change)
  (keyword_modify)
  (keyword_after)
  (keyword_before)
] @keyword

[
  (keyword_range)
  (keyword_rows)
  (keyword_groups)
  (keyword_exclude)
  (keyword_current)
  (keyword_ties)
  (keyword_others)
] @keyword

[
  (keyword_row)
  (keyword_comment)
  (keyword_truncate)
  (keyword_cache)
] @keyword

[
  (keyword_language)
  (keyword_filter)
  (keyword_function)
  (keyword_precision)
  (keyword_restricted)
  (keyword_return)
  (keyword_returns)
  (keyword_separator)
  (keyword_trigger)
  (keyword_unsafe)
] @keyword

[
  (keyword_admin)
  (keyword_connection)
  (keyword_cycle)
  (keyword_database)
  (keyword_encrypted)
  (keyword_increment)
  (keyword_logged)
  (keyword_none)
  (keyword_owned)
  (keyword_password)
  (keyword_reset)
  (keyword_role)
  (keyword_sequence)
  (keyword_start)
  (keyword_restart)
  (keyword_tablespace)
  (keyword_until)
  (keyword_user)
  (keyword_valid)
  (keyword_action)
  (keyword_definer)
  (keyword_invoker)
  (keyword_enable)
  (keyword_disable)
  (keyword_security)
] @keyword

[
  (keyword_out)
  (keyword_inout)
  (keyword_variadic)
  (keyword_ordinality)
] @keyword

[
  (keyword_begin)
  (keyword_commit)
  (keyword_rollback)
  (keyword_transaction)
  (keyword_savepoint)
  (keyword_release)
  (keyword_work)
  (keyword_session)
  (keyword_isolation)
  (keyword_level)
  (keyword_serializable)
  (keyword_repeatable)
  (keyword_read)
  (keyword_write)
  (keyword_committed)
  (keyword_uncommitted)
  (keyword_deferrable)
  (keyword_zone)
  (keyword_immediate)
  (keyword_deferred)
  (keyword_constraints)
  (keyword_snapshot)
  (keyword_characteristics)
] @keyword

[
  (keyword_each)
  (keyword_instead)
  (keyword_of)
  (keyword_initially)
  (keyword_old)
  (keyword_new)
  (keyword_referencing)
  (keyword_statement)
  (keyword_execute)
] @keyword

[
  (keyword_procedure)
  (keyword_percent)
  (keyword_tablesample)
  (keyword_bernoulli)
  (keyword_system)
] @keyword

[
  (keyword_restrict)
  (keyword_unbounded)
  (keyword_unique)
  (keyword_cascade)
  (keyword_check)
  (keyword_option)
  (keyword_wait)
  (keyword_nowait)
  (keyword_maxvalue)
  (keyword_minvalue)
] @type.qualifier

[
  (keyword_int)
  (keyword_null)
  (keyword_boolean)
  (keyword_binary)
  (keyword_varbinary)
  (keyword_bit)
  (keyword_smallint)
  (keyword_bigint)
  (keyword_decimal)
  (keyword_float)
  (keyword_double)
  (keyword_numeric)
  (keyword_real)
  (double)
  (keyword_char)
  (keyword_nchar)
  (keyword_varchar)
  (keyword_nvarchar)
  (keyword_varying)
  (keyword_string)
  (keyword_json)
  (keyword_xml)
  (keyword_enum)
  (keyword_date)
  (keyword_time)
  (keyword_timestamp)
  (keyword_interval)
] @type.builtin

[
  (keyword_in)
  (keyword_and)
  (keyword_or)
  (keyword_not)
  (keyword_by)
  (keyword_on)
  (keyword_union)
  (keyword_except)
  (keyword_intersect)
] @keyword.operator

[
  "+"
  "-"
  "*"
  "/"
  "%"
  "^"
  "="
  "<"
  "<="
  "!="
  ">="
  ">"
  "<>"
  (op_other)
  (op_unary_other)
] @operator

[
  "("
  ")"
] @punctuation.bracket

[
  ";"
  ","
  "."
] @punctuation.delimiter

; ── bigquery/queries/highlights.scm ─────────────────────────────────────────

[
  (keyword_int64)
  (keyword_float64)
  (keyword_bytes)
  (keyword_bignumeric)
  (keyword_geography)
  (keyword_datetime)
] @type.builtin

(keyword_unnest) @function.call

[
  (keyword_search)
  (keyword_vector)
  (keyword_columns)
] @keyword

(keyword_struct) @keyword

(keyword_export) @keyword

(keyword_model) @keyword

(keyword_assert) @keyword

(keyword_continue) @keyword

(keyword_ml) @keyword

(keyword_predict) @keyword

(keyword_evaluate) @keyword

(keyword_error) @keyword

(keyword_source) @keyword

[
  (keyword_call)
  (keyword_raise)
  (keyword_message)
  (keyword_return)
] @keyword

[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

[
  (keyword_access)
  (keyword_aggregate)
  (keyword_assignment)
  (keyword_bi_capacity)
  (keyword_capacity)
  (keyword_clone)
  (keyword_cluster)
  (keyword_copy)
  (keyword_data_policy)
  (keyword_do)
  (keyword_enforced)
  (keyword_exception)
  (keyword_extension)
  (keyword_files)
  (keyword_hash)
  (keyword_include)
  (keyword_iterate)
  (keyword_leave)
  (keyword_load)
  (keyword_loop)
  (keyword_options)
  (keyword_organization)
  (keyword_overwrite)
  (keyword_pivot)
  (keyword_policies)
  (keyword_policy)
  (keyword_project)
  (keyword_qualify)
  (keyword_rebuild)
  (keyword_replica)
  (keyword_reservation)
  (keyword_system_time)
  (keyword_undrop)
  (keyword_unpivot)
  (keyword_while)
] @keyword

[
  (keyword_elseif)
] @conditional
