{
    "targets": [
        {
            "target_name": "tree_sitter_sql_binding",
            "dependencies": [
                "<!(node -p \"require('node-addon-api').targets\"):node_addon_api_except",
            ],
            "include_dirs": [
                "src",
                "spark/src",
                "postgres/src",
                "mysql/src",
                "databricks/src",
                "snowflake/src",
                "bigquery/src",
                "mariadb/src",
                "sqlite/src",
                "hive/src",
                "oracle/src",
                "db2/src",
                "tsql/src",
                "duckdb/src",
                "trino/src",
                "athena/src",
                "redshift/src",
                "clickhouse/src",
                "flink/src",
                "cockroachdb/src",
                "spanner/src",
                "teradata/src",
                "hana/src",
            ],
            "sources": [
                "bindings/node/binding.cc",
                "src/parser.c",
                "src/scanner.c",
                "spark/src/parser.c",
                "spark/src/scanner.c",
                "postgres/src/parser.c",
                "postgres/src/scanner.c",
                "mysql/src/parser.c",
                "mysql/src/scanner.c",
                "databricks/src/parser.c",
                "databricks/src/scanner.c",
                "snowflake/src/parser.c",
                "snowflake/src/scanner.c",
                "bigquery/src/parser.c",
                "bigquery/src/scanner.c",
                "mariadb/src/parser.c",
                "mariadb/src/scanner.c",
                "sqlite/src/parser.c",
                "sqlite/src/scanner.c",
                "hive/src/parser.c",
                "hive/src/scanner.c",
                "oracle/src/parser.c",
                "oracle/src/scanner.c",
                "db2/src/parser.c",
                "db2/src/scanner.c",
                "tsql/src/parser.c",
                "tsql/src/scanner.c",
                "duckdb/src/parser.c",
                "duckdb/src/scanner.c",
                "trino/src/parser.c",
                "trino/src/scanner.c",
                "athena/src/parser.c",
                "athena/src/scanner.c",
                "redshift/src/parser.c",
                "redshift/src/scanner.c",
                "clickhouse/src/parser.c",
                "clickhouse/src/scanner.c",
                "flink/src/parser.c",
                "flink/src/scanner.c",
                "cockroachdb/src/parser.c",
                "cockroachdb/src/scanner.c",
                "spanner/src/parser.c",
                "spanner/src/scanner.c",
                "teradata/src/parser.c",
                "teradata/src/scanner.c",
                "hana/src/parser.c",
                "hana/src/scanner.c",
            ],
            "conditions": [
                ["OS!='win'", {
                    "cflags_c": [
                        "-std=c11",
                    ],
                }, {  # OS == "win"
                    "cflags_c": [
                      "/std:c11",
                      "/utf-8",
                    ],
                }],
            ],
        }
    ]
}
