; GENERATED by scripts/bundle-highlights.js - do not edit.
;
; Standalone highlights query for cockroachdb: base -> postgres -> cockroachdb,
; with every pattern the cockroachdb grammar cannot compile removed. Edit the
; queries/highlights.scm files listed below, then rerun the script.

; ── queries/highlights.scm ──────────────────────────────────────────────────

(object_reference
  name: (identifier) @type)

(invocation
  (object_reference
    name: (identifier) @function.call))

[
  (keyword_array)
] @function.call

(relation
  alias: (identifier) @variable)

(field
  name: (identifier) @field)

(term
  alias: (identifier) @variable)

((term
   value: (cast
    name: (keyword_cast) @function.call
    parameter: [(literal)]?)))

(literal) @string

(comment) @comment @spell

(marginalia) @comment

((literal) @number
   (#match? @number "^[-+]?%d+$"))

((literal) @float
  (#match? @float "^[-+]?%d*\.%d*$"))

(parameter) @parameter

[
  (keyword_true)
  (keyword_false)
] @boolean

[
  (keyword_asc)
  (keyword_desc)
  (keyword_nulls)
  (keyword_last)
  (keyword_default)
  (keyword_collate)
  (keyword_concurrently)
  (keyword_always)
  (keyword_generated)
  (keyword_preceding)
  (keyword_following)
  (keyword_first)
  (keyword_current_timestamp)
  (keyword_immutable)
  (keyword_atomic)
  (keyword_parallel)
  (keyword_leakproof)
  (keyword_safe)
  (keyword_cost)
  (keyword_strict)
] @attribute

[
  (keyword_materialized)
  (keyword_recursive)
  (keyword_temp)
  (keyword_temporary)
  (keyword_unlogged)
  (keyword_external)
  (keyword_volatile)
] @storageclass

[
  (keyword_case)
  (keyword_when)
  (keyword_then)
  (keyword_else)
] @conditional

[
  (keyword_select)
  (keyword_from)
  (keyword_where)
  (keyword_index)
  (keyword_join)
  (keyword_primary)
  (keyword_delete)
  (keyword_create)
  (keyword_insert)
  (keyword_merge)
  (keyword_distinct)
  (keyword_replace)
  (keyword_update)
  (keyword_into)
  (keyword_matched)
  (keyword_values)
  (keyword_value)
  (keyword_attribute)
  (keyword_set)
] @keyword

[
  (keyword_left)
  (keyword_right)
  (keyword_outer)
  (keyword_inner)
  (keyword_full)
] @keyword

[
  (keyword_order)
  (keyword_partition)
  (keyword_group)
  (keyword_rollup)
  (keyword_cube)
  (keyword_grouping)
  (keyword_sets)
  (keyword_with)
  (keyword_without)
  (keyword_as)
  (keyword_having)
  (keyword_limit)
  (keyword_offset)
  (keyword_fetch)
  (keyword_declare)
  (keyword_cursor)
  (keyword_scroll)
  (keyword_next)
  (keyword_within)
] @keyword

[
  (keyword_table)
  (keyword_tables)
  (keyword_key)
  (keyword_references)
  (keyword_usage)
  (keyword_grant)
  (keyword_revoke)
  (keyword_privileges)
  (keyword_public)
  (keyword_foreign)
  (keyword_constraint)
  (keyword_force)
  (keyword_for)
  (keyword_if)
  (keyword_exists)
  (keyword_column)
  (keyword_cross)
  (keyword_lateral)
  (keyword_natural)
  (keyword_alter)
  (keyword_drop)
  (keyword_add)
  (keyword_view)
  (keyword_end)
  (keyword_is)
  (keyword_using)
  (keyword_between)
  (keyword_window)
  (keyword_no)
  (keyword_data)
  (keyword_type)
  (keyword_rename)
  (keyword_refresh)
  (keyword_to)
  (keyword_schema)
  (keyword_owner)
  (keyword_authorization)
] @keyword

[
  (keyword_all)
  (keyword_any)
  (keyword_some)
  (keyword_only)
  (keyword_like)
  (keyword_escape)
  (keyword_rlike)
  (keyword_similar)
  (keyword_over)
  (keyword_change)
  (keyword_modify)
  (keyword_after)
  (keyword_before)
] @keyword

[
  (keyword_range)
  (keyword_rows)
  (keyword_groups)
  (keyword_exclude)
  (keyword_current)
  (keyword_ties)
  (keyword_others)
] @keyword

[
  (keyword_row)
  (keyword_comment)
  (keyword_truncate)
  (keyword_cache)
] @keyword

[
  (keyword_language)
  (keyword_called)
  (keyword_filter)
  (keyword_function)
  (keyword_input)
  (keyword_precision)
  (keyword_restricted)
  (keyword_return)
  (keyword_returns)
  (keyword_separator)
  (keyword_setof)
  (keyword_stable)
  (keyword_support)
  (keyword_trigger)
  (keyword_unsafe)
] @keyword

[
  (keyword_admin)
  (keyword_connection)
  (keyword_cycle)
  (keyword_database)
  (keyword_encrypted)
  (keyword_increment)
  (keyword_logged)
  (keyword_none)
  (keyword_owned)
  (keyword_password)
  (keyword_reset)
  (keyword_role)
  (keyword_sequence)
  (keyword_start)
  (keyword_restart)
  (keyword_tablespace)
  (keyword_until)
  (keyword_user)
  (keyword_valid)
  (keyword_action)
  (keyword_definer)
  (keyword_invoker)
  (keyword_enable)
  (keyword_disable)
  (keyword_security)
] @keyword

[
  (keyword_out)
  (keyword_inout)
  (keyword_variadic)
  (keyword_ordinality)
] @keyword

[
  (keyword_begin)
  (keyword_commit)
  (keyword_rollback)
  (keyword_transaction)
  (keyword_savepoint)
  (keyword_release)
  (keyword_work)
  (keyword_session)
  (keyword_isolation)
  (keyword_level)
  (keyword_serializable)
  (keyword_repeatable)
  (keyword_read)
  (keyword_write)
  (keyword_committed)
  (keyword_uncommitted)
  (keyword_deferrable)
  (keyword_zone)
  (keyword_immediate)
  (keyword_deferred)
  (keyword_constraints)
  (keyword_snapshot)
  (keyword_characteristics)
] @keyword

[
  (keyword_each)
  (keyword_instead)
  (keyword_of)
  (keyword_initially)
  (keyword_old)
  (keyword_new)
  (keyword_referencing)
  (keyword_statement)
  (keyword_execute)
] @keyword

[
  (keyword_procedure)
  (keyword_system)
] @keyword

[
  (keyword_restrict)
  (keyword_unbounded)
  (keyword_unique)
  (keyword_cascade)
  (keyword_check)
  (keyword_option)
  (keyword_local)
  (keyword_cascaded)
  (keyword_wait)
  (keyword_nowait)
  (keyword_maxvalue)
  (keyword_minvalue)
] @type.qualifier

[
  (keyword_int)
  (keyword_null)
  (keyword_boolean)
  (keyword_binary)
  (keyword_varbinary)
  (keyword_bit)
  (keyword_smallint)
  (keyword_bigint)
  (keyword_decimal)
  (keyword_float)
  (keyword_double)
  (keyword_numeric)
  (keyword_real)
  (double)
  (keyword_char)
  (keyword_nchar)
  (keyword_varchar)
  (keyword_nvarchar)
  (keyword_varying)
  (keyword_string)
  (keyword_json)
  (keyword_xml)
  (keyword_enum)
  (keyword_date)
  (keyword_time)
  (keyword_timestamp)
  (keyword_interval)
] @type.builtin

[
  (keyword_in)
  (keyword_and)
  (keyword_or)
  (keyword_not)
  (keyword_by)
  (keyword_on)
  (keyword_union)
  (keyword_except)
  (keyword_intersect)
] @keyword.operator

[
  "+"
  "-"
  "*"
  "/"
  "%"
  "^"
  "="
  "<"
  "<="
  "!="
  ">="
  ">"
  "<>"
  (op_other)
  (op_unary_other)
] @operator

[
  "("
  ")"
] @punctuation.bracket

[
  ";"
  ","
  "."
] @punctuation.delimiter

; ── postgres/queries/highlights.scm ─────────────────────────────────────────

[
  (keyword_btree)
  (keyword_gist)
  (keyword_spgist)
  (keyword_gin)
  (keyword_brin)
] @function.call

[
  (keyword_inherits)
  (keyword_including)
  (keyword_excluding)
] @keyword

[
  (keyword_reindex)
  (keyword_cluster)
  (keyword_checkpoint)
  (keyword_discard)
  (keyword_plans)
  (keyword_sequences)
  (keyword_load)
  (keyword_close)
  (keyword_abort)
  (keyword_chain)
  (keyword_move)
  (keyword_prior)
  (keyword_absolute)
  (keyword_relative)
  (keyword_forward)
  (keyword_backward)
] @keyword

[
  (keyword_label)
  (keyword_reassign)
  (keyword_import)
  (keyword_collation)
  (keyword_conversion)
  (keyword_method)
  (keyword_handler)
  (keyword_transform)
  (keyword_sql)
  (keyword_event)
  (keyword_procedural)
  (keyword_large)
  (keyword_object)
  (keyword_routine)
  (keyword_operator)
  (keyword_rule)
  (keyword_also)
  (keyword_replica)
] @keyword

(operator_symbol) @operator

[
  (keyword_publication)
  (keyword_subscription)
  (keyword_search)
  (keyword_breadth)
  (keyword_depth)
] @keyword

[
  (keyword_listen)
  (keyword_notify)
  (keyword_unlisten)
] @keyword

[
  (keyword_share)
  (keyword_lock)
  (keyword_locked)
  (keyword_skip)
  (keyword_mode)
  (keyword_access)
  (keyword_exclusive)
  (keyword_prepare)
  (keyword_deallocate)
  (keyword_call)
  (keyword_costs)
  (keyword_settings)
  (keyword_generic_plan)
  (keyword_buffers)
  (keyword_wal)
  (keyword_timing)
  (keyword_summary)
  (keyword_yaml)
  (keyword_sequences)
  (keyword_functions)
  (keyword_procedures)
  (keyword_routines)
  (keyword_ilike)
] @keyword

[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

[
  (keyword_aggregate)
  (keyword_assignment)
  (keyword_comments)
  (keyword_compression)
  (keyword_conflict)
  (keyword_copy)
  (keyword_csv)
  (keyword_defaults)
  (keyword_delimiter)
  (keyword_depends)
  (keyword_do)
  (keyword_domain)
  (keyword_encoding)
  (keyword_extended)
  (keyword_extension)
  (keyword_force_not_null)
  (keyword_force_null)
  (keyword_force_quote)
  (keyword_format)
  (keyword_freeze)
  (keyword_hash)
  (keyword_header)
  (keyword_hold)
  (keyword_identity)
  (keyword_implicit)
  (keyword_include)
  (keyword_indexes)
  (keyword_list)
  (keyword_main)
  (keyword_match)
  (keyword_modulus)
  (keyword_nothing)
  (keyword_object_id)
  (keyword_off)
  (keyword_options)
  (keyword_permissive)
  (keyword_plain)
  (keyword_policy)
  (keyword_program)
  (keyword_quote)
  (keyword_remainder)
  (keyword_restrictive)
  (keyword_returning)
  (keyword_server)
  (keyword_show)
  (keyword_statistics)
  (keyword_stdin)
  (keyword_stdout)
  (keyword_storage)
  (keyword_text)
  (keyword_vacuum)
  (keyword_version)
  (keyword_wrapper)
] @keyword

[
  (keyword_current_role)
  (keyword_current_user)
  (keyword_session_user)
] @function.builtin

; ── cockroachdb/queries/highlights.scm ──────────────────────────────────────

[
  (keyword_backup)
  (keyword_restore)
  (keyword_import)
  (keyword_changefeed)
  (keyword_upsert)
  (keyword_latest)
  (keyword_csv)
  (keyword_system)
  (keyword_jobs)
  (keyword_users)
  (keyword_databases)
  (keyword_grants)
  (keyword_columns)
  (keyword_storing)
] @keyword

[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

[
  (keyword_at)
  (keyword_availability)
  (keyword_cancel)
  (keyword_configuration)
  (keyword_configure)
  (keyword_convert)
  (keyword_expiration)
  (keyword_export)
  (keyword_failure)
  (keyword_family)
  (keyword_global)
  (keyword_job)
  (keyword_locality)
  (keyword_parent)
  (keyword_pause)
  (keyword_placement)
  (keyword_queries)
  (keyword_query)
  (keyword_region)
  (keyword_regional)
  (keyword_regions)
  (keyword_resume)
  (keyword_scatter)
  (keyword_schedule)
  (keyword_schedules)
  (keyword_sessions)
  (keyword_setting)
  (keyword_split)
  (keyword_survive)
  (keyword_unsplit)
] @keyword
