dialect: hana
engine: SAP HANA Platform
version: "2.0 SPS 08 (2.0.08)"
source: https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/3bc1a0d4611d40c4a6e3fc7c8e80395d.html?version=2.0.08

statements:
  - id: rollback
    name: ROLLBACK
    doc: https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20fcc453751910149557fc90fe781449.html?version=2.0.08
    tier: high
    probes:
      - id: basic
        sql: "ROLLBACK;"
    examples:
      - "ROLLBACK;"

  - id: rollback_to_savepoint
    name: ROLLBACK TO SAVEPOINT
    doc: https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/104ae26787e24bddbda2953c0397b6e8.html?version=2.0.08
    tier: high
    probes:
      - id: basic
        sql: "ROLLBACK TO SAVEPOINT sp1;"
    examples:
      - "ROLLBACK TO SAVEPOINT savepoint1;"
