; inherits: sql

; MySQL-specific type qualifiers
[
  (keyword_delayed)
  (keyword_high_priority)
  (keyword_low_priority)
] @type.qualifier

; MySQL SHOW / DESCRIBE
[
  (keyword_databases)
  (keyword_processlist)
  (keyword_status)
  (keyword_warnings)
  (keyword_errors)
  (keyword_variables)
  (keyword_indexes)
] @keyword

; MySQL Sprint 8 keywords
[
  (keyword_rollup)
  (keyword_event)
  (keyword_every)
  (keyword_starts)
  (keyword_ends)
  (keyword_invisible)
  (keyword_visible)
  (keyword_enclosed)
  (keyword_respect)
  (keyword_completion)
  (keyword_preserve)
  (keyword_slave)
  (keyword_json_table)
  (keyword_path)
  (keyword_infile)
] @keyword

; Locking, SET scopes, user management, maintenance (#101, #102, #106, #107)
[
  (keyword_share)
  (keyword_lock)
  (keyword_locked)
  (keyword_skip)
  (keyword_prepare)
  (keyword_deallocate)
  (keyword_mode)
  (keyword_global)
  (keyword_persist)
  (keyword_persist_only)
  (keyword_names)
  (keyword_expire)
  (keyword_account)
  (keyword_unlock)
  (keyword_identified)
  (keyword_quick)
  (keyword_extended)
  (keyword_fast)
  (keyword_medium)
  (keyword_changed)
  (keyword_upgrade)
  (keyword_histogram)
  (keyword_buckets)
  (keyword_repair)
  (keyword_use_frm)
  (keyword_no_write_to_binlog)
] @keyword

; EXPLAIN prefix (non-ANSI; re-added over the strict ANSI base)
[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

; ============================================================
; Remaining mysql keywords
; ============================================================

[
  (keyword_against)
  (keyword_algorithm)
  (keyword_at)
  (keyword_auto_increment)
  (keyword_backup)
  (keyword_call)
  (keyword_character)
  (keyword_checksum)
  (keyword_clone)
  (keyword_close)
  (keyword_coalesce)
  (keyword_columns)
  (keyword_component)
  (keyword_concurrent)
  (keyword_condition)
  (keyword_conflict)
  (keyword_continue)
  (keyword_copy)
  (keyword_datafile)
  (keyword_describe)
  (keyword_diagnostics)
  (keyword_directory)
  (keyword_do)
  (keyword_dumpfile)
  (keyword_duplicate)
  (keyword_encryption)
  (keyword_engine)
  (keyword_escaped)
  (keyword_exclusive)
  (keyword_exit)
  (keyword_expansion)
  (keyword_export)
  (keyword_extension)
  (keyword_fields)
  (keyword_flush)
  (keyword_follows)
  (keyword_found)
  (keyword_get)
  (keyword_grants)
  (keyword_handler)
  (keyword_hash)
  (keyword_help)
  (keyword_ignore)
  (keyword_import)
  (keyword_include)
  (keyword_inplace)
  (keyword_install)
  (keyword_instance)
  (keyword_iterate)
  (keyword_keys)
  (keyword_kill)
  (keyword_leave)
  (keyword_less)
  (keyword_linear)
  (keyword_lines)
  (keyword_list)
  (keyword_load)
  (keyword_logfile)
  (keyword_loop)
  (keyword_match)
  (keyword_message_text)
  (keyword_nothing)
  (keyword_open)
  (keyword_optimize)
  (keyword_optionally)
  (keyword_options)
  (keyword_outfile)
  (keyword_partitioning)
  (keyword_partitions)
  (keyword_plugin)
  (keyword_precedes)
  (keyword_prev)
  (keyword_query)
  (keyword_rebuild)
  (keyword_reference)
  (keyword_remove)
  (keyword_reorganize)
  (keyword_repeat)
  (keyword_require)
  (keyword_resignal)
  (keyword_resource)
  (keyword_returned_sqlstate)
  (keyword_schedule)
  (keyword_server)
  (keyword_shared)
  (keyword_show)
  (keyword_shutdown)
  (keyword_signal)
  (keyword_soname)
  (keyword_spatial)
  (keyword_sql)
  (keyword_sqlexception)
  (keyword_sqlstate)
  (keyword_sqlwarning)
  (keyword_ssl)
  (keyword_starting)
  (keyword_stored)
  (keyword_straight_join)
  (keyword_temptable)
  (keyword_terminated)
  (keyword_than)
  (keyword_undefined)
  (keyword_undo)
  (keyword_undofile)
  (keyword_uninstall)
  (keyword_use)
  (keyword_virtual)
  (keyword_while)
] @keyword

[
  (keyword_elseif)
] @conditional
