; inherits: sql

; ── Snowflake-specific keywords ─────────────────────────────────────────────

[
  (keyword_at)
  (keyword_before)
  (keyword_qualify)
  (keyword_pivot)
  (keyword_unpivot)
  (keyword_include)
  (keyword_exclude)
  (keyword_match_recognize)
  (keyword_measures)
  (keyword_pattern)
  (keyword_define)
  (keyword_skip)
  (keyword_one)
  (keyword_per)
  (keyword_past)
  (keyword_next)
  (keyword_let)
  (keyword_raise)
  (keyword_exception)
  (keyword_declare)
  (keyword_execute)
  (keyword_immediate)
  (keyword_task)
  (keyword_copy)
  (keyword_stream)
  (keyword_dynamic)
  (keyword_warehouse)
  (keyword_schedule)
  (keyword_secure)
  (keyword_masking)
  (keyword_target_lag)
  (keyword_access)
  (keyword_storage)
  (keyword_api)
  (keyword_notification)
  (keyword_enabled)
  (keyword_secondary)
  (keyword_roles)
  (keyword_returns)
  (keyword_session)
  (keyword_modify)
] @keyword

; ── Stage references (@stage_name) ─────────────────────────────────────────

(stage_ref) @string.special

; Snowflake STAGE DDL keywords
[
  (keyword_stage)
  (keyword_url)
  (keyword_credentials)
  (keyword_file_format)
  (keyword_copy_options)
  (keyword_directory)
  (keyword_encryption)
  (keyword_pattern)
  (keyword_list)
] @keyword

; EXPLAIN prefix (non-ANSI; re-added over the strict ANSI base)
[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

; ============================================================
; Remaining snowflake keywords
; ============================================================

[
  (keyword_abort)
  (keyword_account)
  (keyword_auto_resume)
  (keyword_auto_suspend)
  (keyword_call)
  (keyword_catalog)
  (keyword_clone)
  (keyword_cluster)
  (keyword_clustering)
  (keyword_columns)
  (keyword_connect)
  (keyword_databases)
  (keyword_describe)
  (keyword_do)
  (keyword_economy)
  (keyword_extension)
  (keyword_file)
  (keyword_files)
  (keyword_format)
  (keyword_formats)
  (keyword_functions)
  (keyword_get)
  (keyword_grants)
  (keyword_hash)
  (keyword_ignore)
  (keyword_ilike)
  (keyword_integration)
  (keyword_integrations)
  (keyword_location)
  (keyword_locks)
  (keyword_match)
  (keyword_max_cluster_count)
  (keyword_min_cluster_count)
  (keyword_nocycle)
  (keyword_overwrite)
  (keyword_parameters)
  (keyword_pipe)
  (keyword_pipes)
  (keyword_policies)
  (keyword_policy)
  (keyword_prior)
  (keyword_procedures)
  (keyword_put)
  (keyword_queries)
  (keyword_remove)
  (keyword_resume)
  (keyword_returning)
  (keyword_scaling_policy)
  (keyword_schemas)
  (keyword_sequences)
  (keyword_show)
  (keyword_stages)
  (keyword_standard)
  (keyword_starts)
  (keyword_streams)
  (keyword_suspend)
  (keyword_swap)
  (keyword_tasks)
  (keyword_terse)
  (keyword_transactions)
  (keyword_undrop)
  (keyword_unset)
  (keyword_use)
  (keyword_users)
  (keyword_views)
  (keyword_warehouse_size)
  (keyword_warehouses)
] @keyword
