; inherits: sql

; Db2-specific keywords
[
  (keyword_prepare)
  (keyword_component)
  (keyword_components)
  (keyword_override)
  (keyword_authorized)
  (keyword_tree)
  (keyword_append)
  (keyword_activate)
  (keyword_reorg)
  (keyword_indexes)
  (keyword_wrapper)
  (keyword_nickname)
  (keyword_module)
  (keyword_server)
  (keyword_mask)
  (keyword_permission)
  (keyword_transfer)
  (keyword_ownership)
  (keyword_enforced)
  (keyword_ur)
  (keyword_cs)
  (keyword_rs)
  (keyword_rr)
  (keyword_do)
  (keyword_leave)
  (keyword_iterate)
  (keyword_loop)
  (keyword_elseif)
  (keyword_while)
  (keyword_declare)
  (keyword_atomic)
] @keyword

; Db2 cursor lifecycle and FOR loop (#99)
[
  (keyword_cursor)
  (keyword_open)
  (keyword_close)
  (keyword_hold)
] @keyword

; Data-change-table-reference (#123)
[
  (keyword_final)
] @keyword

; EXPLAIN prefix (non-ANSI; re-added over the strict ANSI base)
[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

; ============================================================
; Remaining db2 keywords
; ============================================================

[
  (keyword_access)
  (keyword_age)
  (keyword_alias)
  (keyword_allocate)
  (keyword_allow)
  (keyword_asensitive)
  (keyword_associate)
  (keyword_audit)
  (keyword_authentication)
  (keyword_begin_declare_section)
  (keyword_buffer)
  (keyword_bufferpools)
  (keyword_business_time)
  (keyword_call)
  (keyword_caller)
  (keyword_capture)
  (keyword_categories)
  (keyword_changes)
  (keyword_checked)
  (keyword_client)
  (keyword_compress)
  (keyword_connect)
  (keyword_constant)
  (keyword_context)
  (keyword_continue)
  (keyword_cursors)
  (keyword_datalake)
  (keyword_describe)
  (keyword_diagnostics)
  (keyword_dimensions)
  (keyword_disconnect)
  (keyword_dynamic)
  (keyword_end_declare_section)
  (keyword_event)
  (keyword_exception)
  (keyword_exclusive)
  (keyword_extension)
  (keyword_failure)
  (keyword_federated)
  (keyword_flush)
  (keyword_format)
  (keyword_found)
  (keyword_free)
  (keyword_get)
  (keyword_global)
  (keyword_go)
  (keyword_goto)
  (keyword_hash)
  (keyword_hierarchy)
  (keyword_identity)
  (keyword_ignore)
  (keyword_include)
  (keyword_incremental)
  (keyword_insensitive)
  (keyword_integrity)
  (keyword_label)
  (keyword_location)
  (keyword_locator)
  (keyword_locators)
  (keyword_lock)
  (keyword_locks)
  (keyword_mapping)
  (keyword_message_text)
  (keyword_method)
  (keyword_mode)
  (keyword_modification)
  (keyword_monitor)
  (keyword_off)
  (keyword_optimization)
  (keyword_optimize)
  (keyword_options)
  (keyword_organize)
  (keyword_output)
  (keyword_package)
  (keyword_partitioned)
  (keyword_path)
  (keyword_pipe)
  (keyword_policy)
  (keyword_preserve)
  (keyword_profile)
  (keyword_query)
  (keyword_remove)
  (keyword_repeat)
  (keyword_resignal)
  (keyword_result)
  (keyword_retain)
  (keyword_reuse)
  (keyword_scope)
  (keyword_share)
  (keyword_signal)
  (keyword_sql)
  (keyword_sqlerror)
  (keyword_sqlstate)
  (keyword_sqlwarning)
  (keyword_status)
  (keyword_storage)
  (keyword_stored)
  (keyword_success)
  (keyword_system_time)
  (keyword_tblproperties)
  (keyword_tracking)
  (keyword_triggers)
  (keyword_trusted)
  (keyword_unchecked)
  (keyword_variable)
  (keyword_version)
  (keyword_whenever)
  (keyword_xsrobject)
  (keyword_yes)
] @keyword

[
  (keyword_current_user)
  (keyword_session_user)
  (keyword_system_user)
] @function.builtin
