; inherits: sql

; SAP HANA-specific keywords
[
  (keyword_upsert)
  (keyword_locked)
  (keyword_hint)
  (keyword_sqlscript)
  (keyword_invoker)
  (keyword_definer)
  (keyword_reads)
  (keyword_declare)
  (keyword_constant)
  (keyword_inout)
  (keyword_global)
  (keyword_sql)
  (keyword_priority)
  (keyword_log)
  (keyword_persistent)
  (keyword_memory)
  (keyword_off)
] @keyword

; EXPLAIN prefix (non-ANSI; re-added over the strict ANSI base)
[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

; ============================================================
; Remaining hana keywords
; ============================================================

[
  (keyword_annotate)
  (keyword_anonymization)
  (keyword_assertion)
  (keyword_async)
  (keyword_at)
  (keyword_audit)
  (keyword_break)
  (keyword_call)
  (keyword_cancel)
  (keyword_certificate)
  (keyword_class)
  (keyword_connect)
  (keyword_continue)
  (keyword_credential)
  (keyword_delta)
  (keyword_do)
  (keyword_exclusive)
  (keyword_export)
  (keyword_extension)
  (keyword_file)
  (keyword_hash)
  (keyword_ignore)
  (keyword_import)
  (keyword_include)
  (keyword_job)
  (keyword_jwt)
  (keyword_ldap)
  (keyword_load)
  (keyword_loadable)
  (keyword_location)
  (keyword_lock)
  (keyword_mapping)
  (keyword_mode)
  (keyword_online)
  (keyword_page)
  (keyword_parameters)
  (keyword_part)
  (keyword_policy)
  (keyword_preferred)
  (keyword_provider)
  (keyword_pse)
  (keyword_purpose)
  (keyword_rdf)
  (keyword_rebuild)
  (keyword_remote)
  (keyword_remove)
  (keyword_reverse)
  (keyword_rolegroup)
  (keyword_saml)
  (keyword_scan)
  (keyword_scheduler)
  (keyword_share)
  (keyword_source)
  (keyword_sparql_graph)
  (keyword_statistics)
  (keyword_synonym)
  (keyword_top)
  (keyword_unload)
  (keyword_unset)
  (keyword_usergroup)
  (keyword_validate)
  (keyword_vector)
  (keyword_while)
  (keyword_workload)
  (keyword_x509)
] @keyword

[
  (keyword_elseif)
] @conditional
