import { make_keyword } from "./helpers.js";

// ─── Architecture note ────────────────────────────────────────────────────────
// This file contains ANSI SQL keywords and keywords required by base grammar
// rules.  Non-ANSI, dialect-specific keywords belong in each dialect's own
// grammar.js, not here.  Each dialect independently declares the keywords it
// needs; inheritance flows base → x → y only.  Duplication across dialects is
// intentional and preferred over a shared keyword pool.
// ─────────────────────────────────────────────────────────────────────────────

export default {

  keyword_select: _ => make_keyword("select"),
  keyword_delete: _ => make_keyword("delete"),
  keyword_insert: _ => make_keyword("insert"),
  keyword_replace: _ => make_keyword("replace"),
  keyword_update: _ => make_keyword("update"),
  keyword_truncate: _ => make_keyword("truncate"),
  keyword_merge: _ => make_keyword("merge"),
  keyword_into: _ => make_keyword("into"),
  keyword_values: _ => make_keyword("values"),
  keyword_value: _ => make_keyword("value"),
  keyword_matched: _ => make_keyword("matched"),
  keyword_set: _ => make_keyword("set"),
  keyword_from: _ => make_keyword("from"),
  keyword_left: _ => make_keyword("left"),
  keyword_right: _ => make_keyword("right"),
  keyword_inner: _ => make_keyword("inner"),
  keyword_full: _ => make_keyword("full"),
  keyword_outer: _ => make_keyword("outer"),
  keyword_cross: _ => make_keyword("cross"),
  keyword_join: _ => make_keyword("join"),
  keyword_lateral: _ => make_keyword("lateral"),
  keyword_natural: _ => make_keyword("natural"),
  keyword_on: _ => make_keyword("on"),
  keyword_where: _ => make_keyword("where"),
  keyword_order: _ => make_keyword("order"),
  keyword_group: _ => make_keyword("group"),
  keyword_partition: _ => make_keyword("partition"),
  keyword_by: _ => make_keyword("by"),
  keyword_having: _ => make_keyword("having"),
  keyword_desc: _ => make_keyword("desc"),
  keyword_asc: _ => make_keyword("asc"),
  keyword_limit: _ => make_keyword("limit"),
  keyword_offset: _ => make_keyword("offset"),
  keyword_primary: _ => make_keyword("primary"),
  keyword_create: _ => make_keyword("create"),
  keyword_alter: _ => make_keyword("alter"),
  keyword_change: _ => make_keyword("change"),
  keyword_analyze: _ => make_keyword("analyze"),
  keyword_explain: _ => make_keyword("explain"),
  keyword_verbose: _ => make_keyword("verbose"),
  keyword_modify: _ => make_keyword("modify"),
  keyword_drop: _ => make_keyword("drop"),
  keyword_add: _ => make_keyword("add"),
  keyword_table: _ => make_keyword("table"),
  keyword_tables: _ => make_keyword("tables"),
  keyword_view: _ => make_keyword("view"),
  keyword_column: _ => make_keyword("column"),
  keyword_materialized: _ => make_keyword("materialized"),
  keyword_tablespace: _ => make_keyword("tablespace"),
  keyword_sequence: _ => make_keyword("sequence"),
  keyword_increment: _ => make_keyword("increment"),
  keyword_minvalue: _ => make_keyword("minvalue"),
  keyword_maxvalue: _ => make_keyword("maxvalue"),
  keyword_none: _ => make_keyword("none"),
  keyword_owned: _ => make_keyword("owned"),
  keyword_start: _ => make_keyword("start"),
  keyword_restart: _ => make_keyword("restart"),
  keyword_usage: _ => make_keyword("usage"),
  keyword_rollup: _ => make_keyword("rollup"),
  keyword_cube: _ => make_keyword("cube"),
  keyword_grouping: _ => make_keyword("grouping"),
  keyword_sets: _ => make_keyword("sets"),
  keyword_key: _ => make_keyword("key"),
  keyword_duplicate: _ => make_keyword("duplicate"),
  keyword_as: _ => make_keyword("as"),
  keyword_distinct: _ => make_keyword("distinct"),
  keyword_constraint: _ => make_keyword("constraint"),
  keyword_filter: _ => make_keyword("filter"),
  keyword_cast: _ => make_keyword("cast"),
  keyword_separator: _ => make_keyword("separator"),
  keyword_case: _ => make_keyword("case"),
  keyword_when: _ => make_keyword("when"),
  keyword_then: _ => make_keyword("then"),
  keyword_else: _ => make_keyword("else"),
  keyword_end: _ => make_keyword("end"),
  keyword_in: _ => make_keyword("in"),
  keyword_and: _ => make_keyword("and"),
  keyword_or: _ => make_keyword("or"),
  keyword_is: _ => make_keyword("is"),
  keyword_not: _ => make_keyword("not"),
  keyword_enable: _ => make_keyword("enable"),
  keyword_disable: _ => make_keyword("disable"),
  keyword_force: _ => make_keyword("force"),
  keyword_ignore: _ => make_keyword("ignore"),
  keyword_using: _ => make_keyword("using"),
  keyword_use: _ => make_keyword("use"),
  keyword_index: _ => make_keyword("index"),
  keyword_include: _ => make_keyword("include"),
  keyword_for: _ => make_keyword("for"),
  keyword_if: _ => make_keyword("if"),
  keyword_exists: _ => make_keyword("exists"),
  keyword_generated: _ => make_keyword("generated"),
  keyword_always: _ => make_keyword("always"),
  keyword_collate: _ => make_keyword("collate"),
  keyword_character: _ => make_keyword("character"),
  keyword_default: _ => make_keyword("default"),
  keyword_cascade: _ => make_keyword("cascade"),
  keyword_restrict: _ => make_keyword("restrict"),
  keyword_with: _ => make_keyword("with"),
  keyword_without: _ => make_keyword("without"),
  keyword_no: _ => make_keyword("no"),
  keyword_data: _ => make_keyword("data"),
  keyword_type: _ => make_keyword("type"),
  keyword_refresh: _ => make_keyword("refresh"),
  keyword_rename: _ => make_keyword("rename"),
  keyword_to: _ => make_keyword("to"),
  keyword_database: _ => make_keyword("database"),
  keyword_schema: _ => make_keyword("schema"),
  keyword_public: _ => make_keyword("public"),
  keyword_owner: _ => make_keyword("owner"),
  keyword_user: _ => make_keyword("user"),
  keyword_admin: _ => make_keyword("admin"),
  keyword_password: _ => make_keyword("password"),
  keyword_encrypted: _ => make_keyword("encrypted"),
  keyword_valid: _ => make_keyword("valid"),
  keyword_until: _ => make_keyword("until"),
  keyword_connection: _ => make_keyword("connection"),
  keyword_role: _ => make_keyword("role"),
  keyword_reset: _ => make_keyword("reset"),
  keyword_temp: _ => make_keyword("temp"),
  keyword_temporary: _ => make_keyword("temporary"),
  keyword_unlogged: _ => make_keyword("unlogged"),
  keyword_logged: _ => make_keyword("logged"),
  keyword_cycle: _ => make_keyword("cycle"),
  keyword_union: _ => make_keyword("union"),
  keyword_all: _ => make_keyword("all"),
  keyword_any: _ => make_keyword("any"),
  keyword_some: _ => make_keyword("some"),
  keyword_intersect: _ => make_keyword("intersect"),
  keyword_returning: _ => make_keyword("returning"),
  keyword_begin: _ => make_keyword("begin"),
  keyword_commit: _ => make_keyword("commit"),
  keyword_rollback: _ => make_keyword("rollback"),
  keyword_transaction: _ => make_keyword("transaction"),
  keyword_over: _ => make_keyword("over"),
  keyword_nulls: _ => make_keyword("nulls"),
  keyword_first: _ => make_keyword("first"),
  keyword_after: _ => make_keyword("after"),
  keyword_before: _ => make_keyword("before"),
  keyword_last: _ => make_keyword("last"),
  keyword_window: _ => make_keyword("window"),
  keyword_range: _ => make_keyword("range"),
  keyword_groups: _ => make_keyword("groups"),
  keyword_between: _ => make_keyword("between"),
  keyword_unbounded: _ => make_keyword("unbounded"),
  keyword_preceding: _ => make_keyword("preceding"),
  keyword_following: _ => make_keyword("following"),
  keyword_exclude: _ => make_keyword("exclude"),
  keyword_current: _ => make_keyword("current"),
  keyword_row: _ => make_keyword("row"),
  keyword_fetch: _ => make_keyword("fetch"),
  keyword_ties: _ => make_keyword("ties"),
  keyword_others: _ => make_keyword("others"),
  keyword_only: _ => make_keyword("only"),
  keyword_unique: _ => make_keyword("unique"),
  keyword_foreign: _ => make_keyword("foreign"),
  keyword_references: _ => make_keyword("references"),
  keyword_concurrently: _ => make_keyword("concurrently"),
  keyword_hash: _ => make_keyword("hash"),
  keyword_like: _ => make_keyword("like"),
  keyword_rlike: _ => choice(make_keyword("rlike"),make_keyword("regexp")),
  keyword_similar: _ => make_keyword("similar"),

  keyword_conflict: _ => make_keyword("conflict"),
  keyword_do: _ => make_keyword("do"),
  keyword_nothing: _ => make_keyword("nothing"),
  keyword_recursive: _ => make_keyword("recursive"),
  keyword_cascaded: _ => make_keyword("cascaded"),
  keyword_local: _ => make_keyword("local"),
  keyword_current_timestamp: _ => make_keyword("current_timestamp"),
  keyword_check: _ => make_keyword("check"),
  keyword_option: _ => make_keyword("option"),
  keyword_wait: _ => make_keyword("wait"),
  keyword_nowait: _ => make_keyword("nowait"),
  keyword_attribute: _ => make_keyword("attribute"),
  keyword_authorization: _ => make_keyword("authorization"),
  keyword_action: _ => make_keyword("action"),

  // ANSI SQL grant/revoke/catalog
  keyword_grant: _ => make_keyword("grant"),
  keyword_revoke: _ => make_keyword("revoke"),
  keyword_privileges: _ => make_keyword("privileges"),
  keyword_catalog: _ => make_keyword("catalog"),

  // ANSI SQL — tablesample/percent (used in base grammar tablesample rule)
  keyword_tablesample: _ => make_keyword("tablesample"),
  keyword_percent: _ => make_keyword("percent"),

  // Common dialect type — string (used in base _type rule)
  keyword_string: _ => make_keyword("string"),

  // ANSI SQL — FETCH NEXT n ROWS
  keyword_next: _ => make_keyword("next"),

  keyword_except: _ => make_keyword("except"),

  keyword_trigger: _ => make_keyword('trigger'),
  keyword_function: _ => make_keyword("function"),
  keyword_returns: _ => make_keyword("returns"),
  keyword_return: _ => make_keyword("return"),
  keyword_setof: _ => make_keyword("setof"),
  keyword_atomic: _ => make_keyword("atomic"),
  keyword_language: _ => make_keyword("language"),
  keyword_immutable: _ => make_keyword("immutable"),
  keyword_stable: _ => make_keyword("stable"),
  keyword_volatile: _ => make_keyword("volatile"),
  keyword_leakproof: _ => make_keyword("leakproof"),
  keyword_parallel: _ => make_keyword("parallel"),
  keyword_safe: _ => make_keyword("safe"),
  keyword_unsafe: _ => make_keyword("unsafe"),
  keyword_restricted: _ => make_keyword("restricted"),
  keyword_called: _ => make_keyword("called"),
  keyword_input: _ => make_keyword("input"),
  keyword_strict: _ => make_keyword("strict"),
  keyword_cost: _ => make_keyword("cost"),
  keyword_rows: _ => make_keyword("rows"),
  keyword_support: _ => make_keyword("support"),
  keyword_definer: _ => make_keyword("definer"),
  keyword_invoker: _ => make_keyword("invoker"),
  keyword_security: _ => make_keyword("security"),
  keyword_extension: _ => make_keyword("extension"),
  keyword_out: _ => make_keyword("out"),
  keyword_inout: _ => make_keyword("inout"),
  keyword_variadic: _ => make_keyword("variadic"),
  keyword_ordinality: _ => make_keyword("ordinality"),

  keyword_session: _ => make_keyword("session"),
  keyword_isolation: _ => make_keyword("isolation"),
  keyword_level: _ => make_keyword("level"),
  keyword_serializable: _ => make_keyword("serializable"),
  keyword_repeatable: _ => make_keyword("repeatable"),
  keyword_read: _ => make_keyword("read"),
  keyword_write: _ => make_keyword("write"),
  keyword_committed: _ => make_keyword("committed"),
  keyword_uncommitted: _ => make_keyword("uncommitted"),
  keyword_deferrable: _ => make_keyword("deferrable"),
  keyword_zone: _ => make_keyword("zone"),
  keyword_immediate: _ => make_keyword("immediate"),
  keyword_deferred: _ => make_keyword("deferred"),
  keyword_constraints    : _ => make_keyword("constraints"),
  keyword_snapshot: _ => make_keyword("snapshot"),
  keyword_characteristics: _ => make_keyword("characteristics"),
  keyword_each: _ => make_keyword("each"),
  keyword_instead: _ => make_keyword("instead"),
  keyword_of: _ => make_keyword("of"),
  keyword_initially: _ => make_keyword("initially"),
  keyword_old: _ => make_keyword("old"),
  keyword_new: _ => make_keyword("new"),
  keyword_referencing: _ => make_keyword("referencing"),
  keyword_statement: _ => make_keyword("statement"),
  keyword_execute: _ => make_keyword("execute"),
  keyword_procedure: _ => make_keyword("procedure"),

  // ANSI SQL — used in base CREATE TABLE (CREATE EXTERNAL TABLE)
  keyword_external: _ => make_keyword("external"),
  // ANSI SQL — used in base COMMENT ON statement
  keyword_comment: _ => make_keyword("comment"),
  // ANSI SQL — used in base ALTER SEQUENCE ... CACHE n
  keyword_cache: _ => make_keyword("cache"),

  // Operators
  is_not: $ => prec.left(seq($.keyword_is, $.keyword_not)),
  not_like: $ => seq($.keyword_not, $.keyword_like),
  not_rlike: $ => seq($.keyword_not, $.keyword_rlike),
  similar_to: $ => seq($.keyword_similar, $.keyword_to),
  not_similar_to: $ => seq($.keyword_not, $.keyword_similar, $.keyword_to),
  distinct_from: $ => seq($.keyword_is, $.keyword_distinct, $.keyword_from),
  not_distinct_from: $ => seq($.keyword_is, $.keyword_not, $.keyword_distinct, $.keyword_from),

  _temporary: $ => choice($.keyword_temp, $.keyword_temporary),
  _not_null: $ => seq($.keyword_not, $.keyword_null),
  _primary_key: $ => seq($.keyword_primary, $.keyword_key),
  _if_exists: $ => seq($.keyword_if, $.keyword_exists),
  _if_not_exists: $ => seq($.keyword_if, $.keyword_not, $.keyword_exists),
  _or_replace: $ => seq($.keyword_or, $.keyword_replace),
  _current_row: $ => seq($.keyword_current, $.keyword_row),
  _exclude_current_row: $ => seq($.keyword_exclude, $.keyword_current, $.keyword_row),
  _exclude_group: $ => seq($.keyword_exclude, $.keyword_group),
  _exclude_no_others: $ => seq($.keyword_exclude, $.keyword_no, $.keyword_others),
  _exclude_ties: $ => seq($.keyword_exclude, $.keyword_ties),
  _check_option: $ => seq($.keyword_check, $.keyword_option),
  direction: $ => choice($.keyword_desc, $.keyword_asc),

  // Types
  keyword_null: _ => make_keyword("null"),
  keyword_true: _ => make_keyword("true"),
  keyword_false: _ => make_keyword("false"),

  keyword_boolean: _ => make_keyword("boolean"),
  keyword_bit: _ => make_keyword("bit"),
  keyword_binary: _ => make_keyword("binary"),
  keyword_varbinary: _ => make_keyword("varbinary"),

  keyword_smallint: _ => make_keyword("smallint"),
  keyword_int: _ => choice(make_keyword("int"), make_keyword("integer")),
  keyword_bigint: _ => make_keyword("bigint"),
  keyword_decimal: _ => make_keyword("decimal"),
  keyword_numeric: _ => make_keyword("numeric"),
  keyword_real: _ => make_keyword("real"),
  keyword_float: _ => make_keyword("float"),
  keyword_double: _ => make_keyword("double"),
  keyword_precision: _ => make_keyword("precision"),

  keyword_varying: _ => make_keyword("varying"),

  keyword_char: _ => choice(make_keyword("char"), make_keyword("character")),
  keyword_nchar: _ => make_keyword("nchar"),
  keyword_varchar: $ => choice(
    make_keyword("varchar"),
    seq(
      make_keyword("character"),
      $.keyword_varying,
    )
  ),
  keyword_nvarchar: _ => make_keyword("nvarchar"),

  keyword_json: _ => make_keyword("json"),
  keyword_xml: _ => make_keyword("xml"),

  keyword_enum: _ => make_keyword("enum"),

  keyword_date: _ => make_keyword("date"),
  keyword_time: _ => make_keyword("time"),
  keyword_timestamp: _ => make_keyword("timestamp"),
  keyword_interval: _ => make_keyword("interval"),

  keyword_array: _ => make_keyword("array"), // not included in _type since it's a constructor literal

  // ANSI SQL — TRIM(BOTH|LEADING|TRAILING x FROM y)
  keyword_both: _ => make_keyword("both"),
  keyword_leading: _ => make_keyword("leading"),
  keyword_trailing: _ => make_keyword("trailing"),
  keyword_trim: _ => make_keyword("trim"),

  // ANSI SQL — WITHIN GROUP (ORDER BY ...)
  keyword_within: _ => make_keyword("within"),

}
