; GENERATED by scripts/bundle-highlights.js - do not edit.
;
; Standalone highlights query for spark: base -> hive -> spark,
; with every pattern the spark grammar cannot compile removed. Edit the
; queries/highlights.scm files listed below, then rerun the script.

; ── queries/highlights.scm ──────────────────────────────────────────────────

(object_reference
  name: (identifier) @type)

(invocation
  (object_reference
    name: (identifier) @function.call))

[
  (keyword_array)
] @function.call

(relation
  alias: (identifier) @variable)

(field
  name: (identifier) @field)

(term
  alias: (identifier) @variable)

((term
   value: (cast
    name: (keyword_cast) @function.call
    parameter: [(literal)]?)))

(literal) @string

(comment) @comment @spell

(marginalia) @comment

((literal) @number
   (#match? @number "^[-+]?%d+$"))

((literal) @float
  (#match? @float "^[-+]?%d*\.%d*$"))

(parameter) @parameter

[
  (keyword_true)
  (keyword_false)
] @boolean

[
  (keyword_asc)
  (keyword_desc)
  (keyword_nulls)
  (keyword_last)
  (keyword_default)
  (keyword_collate)
  (keyword_concurrently)
  (keyword_always)
  (keyword_generated)
  (keyword_preceding)
  (keyword_following)
  (keyword_first)
  (keyword_current_timestamp)
  (keyword_immutable)
  (keyword_atomic)
  (keyword_parallel)
  (keyword_leakproof)
  (keyword_safe)
  (keyword_cost)
  (keyword_strict)
] @attribute

[
  (keyword_materialized)
  (keyword_recursive)
  (keyword_temp)
  (keyword_temporary)
  (keyword_unlogged)
  (keyword_external)
  (keyword_volatile)
] @storageclass

[
  (keyword_case)
  (keyword_when)
  (keyword_then)
  (keyword_else)
] @conditional

[
  (keyword_select)
  (keyword_from)
  (keyword_where)
  (keyword_index)
  (keyword_join)
  (keyword_primary)
  (keyword_delete)
  (keyword_create)
  (keyword_insert)
  (keyword_merge)
  (keyword_distinct)
  (keyword_replace)
  (keyword_update)
  (keyword_into)
  (keyword_matched)
  (keyword_values)
  (keyword_value)
  (keyword_attribute)
  (keyword_set)
] @keyword

[
  (keyword_left)
  (keyword_right)
  (keyword_outer)
  (keyword_inner)
  (keyword_full)
] @keyword

[
  (keyword_order)
  (keyword_partition)
  (keyword_group)
  (keyword_rollup)
  (keyword_cube)
  (keyword_grouping)
  (keyword_sets)
  (keyword_with)
  (keyword_without)
  (keyword_as)
  (keyword_having)
  (keyword_limit)
  (keyword_offset)
  (keyword_declare)
  (keyword_within)
] @keyword

[
  (keyword_table)
  (keyword_tables)
  (keyword_key)
  (keyword_references)
  (keyword_usage)
  (keyword_grant)
  (keyword_revoke)
  (keyword_privileges)
  (keyword_public)
  (keyword_foreign)
  (keyword_constraint)
  (keyword_force)
  (keyword_for)
  (keyword_if)
  (keyword_exists)
  (keyword_column)
  (keyword_cross)
  (keyword_lateral)
  (keyword_natural)
  (keyword_alter)
  (keyword_drop)
  (keyword_add)
  (keyword_view)
  (keyword_end)
  (keyword_is)
  (keyword_using)
  (keyword_between)
  (keyword_window)
  (keyword_no)
  (keyword_data)
  (keyword_type)
  (keyword_rename)
  (keyword_refresh)
  (keyword_to)
  (keyword_schema)
  (keyword_owner)
  (keyword_authorization)
] @keyword

[
  (keyword_all)
  (keyword_any)
  (keyword_some)
  (keyword_only)
  (keyword_like)
  (keyword_escape)
  (keyword_rlike)
  (keyword_similar)
  (keyword_over)
  (keyword_change)
  (keyword_modify)
  (keyword_after)
  (keyword_before)
] @keyword

[
  (keyword_range)
  (keyword_rows)
  (keyword_groups)
  (keyword_exclude)
  (keyword_current)
  (keyword_ties)
  (keyword_others)
] @keyword

[
  (keyword_row)
  (keyword_comment)
  (keyword_truncate)
  (keyword_cache)
] @keyword

[
  (keyword_language)
  (keyword_called)
  (keyword_filter)
  (keyword_function)
  (keyword_input)
  (keyword_precision)
  (keyword_restricted)
  (keyword_return)
  (keyword_returns)
  (keyword_separator)
  (keyword_setof)
  (keyword_stable)
  (keyword_support)
  (keyword_trigger)
  (keyword_unsafe)
] @keyword

[
  (keyword_admin)
  (keyword_connection)
  (keyword_cycle)
  (keyword_database)
  (keyword_encrypted)
  (keyword_increment)
  (keyword_logged)
  (keyword_none)
  (keyword_owned)
  (keyword_password)
  (keyword_reset)
  (keyword_role)
  (keyword_sequence)
  (keyword_start)
  (keyword_restart)
  (keyword_tablespace)
  (keyword_until)
  (keyword_user)
  (keyword_valid)
  (keyword_action)
  (keyword_definer)
  (keyword_invoker)
  (keyword_enable)
  (keyword_disable)
  (keyword_security)
] @keyword

[
  (keyword_out)
  (keyword_inout)
  (keyword_variadic)
  (keyword_ordinality)
] @keyword

[
  (keyword_begin)
  (keyword_commit)
  (keyword_rollback)
  (keyword_transaction)
  (keyword_savepoint)
  (keyword_release)
  (keyword_work)
  (keyword_session)
  (keyword_isolation)
  (keyword_level)
  (keyword_serializable)
  (keyword_repeatable)
  (keyword_read)
  (keyword_write)
  (keyword_committed)
  (keyword_uncommitted)
  (keyword_deferrable)
  (keyword_zone)
  (keyword_immediate)
  (keyword_deferred)
  (keyword_constraints)
  (keyword_snapshot)
  (keyword_characteristics)
] @keyword

[
  (keyword_each)
  (keyword_instead)
  (keyword_of)
  (keyword_initially)
  (keyword_old)
  (keyword_new)
  (keyword_referencing)
  (keyword_statement)
  (keyword_execute)
] @keyword

[
  (keyword_procedure)
  (keyword_percent)
  (keyword_tablesample)
] @keyword

[
  (keyword_restrict)
  (keyword_unbounded)
  (keyword_unique)
  (keyword_cascade)
  (keyword_check)
  (keyword_option)
  (keyword_local)
  (keyword_wait)
  (keyword_nowait)
  (keyword_maxvalue)
  (keyword_minvalue)
] @type.qualifier

[
  (keyword_int)
  (keyword_null)
  (keyword_boolean)
  (keyword_binary)
  (keyword_varbinary)
  (keyword_bit)
  (keyword_smallint)
  (keyword_bigint)
  (keyword_decimal)
  (keyword_float)
  (keyword_double)
  (keyword_numeric)
  (keyword_real)
  (double)
  (keyword_char)
  (keyword_nchar)
  (keyword_varchar)
  (keyword_nvarchar)
  (keyword_varying)
  (keyword_string)
  (keyword_json)
  (keyword_xml)
  (keyword_enum)
  (keyword_date)
  (keyword_time)
  (keyword_timestamp)
  (keyword_interval)
] @type.builtin

[
  (keyword_in)
  (keyword_and)
  (keyword_or)
  (keyword_not)
  (keyword_by)
  (keyword_on)
  (keyword_union)
  (keyword_except)
  (keyword_intersect)
] @keyword.operator

[
  "+"
  "-"
  "*"
  "/"
  "%"
  "^"
  "="
  "<"
  "<="
  "!="
  ">="
  ">"
  "<>"
  (op_other)
  (op_unary_other)
] @operator

[
  "("
  ")"
] @punctuation.bracket

[
  ";"
  ","
  "."
] @punctuation.delimiter

; ── hive/queries/highlights.scm ─────────────────────────────────────────────

[
  (keyword_serde)
  (keyword_serdeproperties)
] @keyword

[
  (keyword_transform)
  (keyword_show)
  (keyword_describe)
  (keyword_formatted)
  (keyword_extended)
  (keyword_databases)
  (keyword_schemas)
  (keyword_functions)
] @keyword

[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

[
  (keyword_tinyint)
  (keyword_connectors)
  (keyword_columns)
  (keyword_indexes)
  (keyword_locks)
  (keyword_compactions)
  (keyword_conf)
  (keyword_views)
  (keyword_transactions)
] @keyword

[
  (keyword_avro)
  (keyword_bucket)
  (keyword_buckets)
  (keyword_cached)
  (keyword_catalog)
  (keyword_character)
  (keyword_cluster)
  (keyword_clustered)
  (keyword_conflict)
  (keyword_csv)
  (keyword_dbproperties)
  (keyword_delimited)
  (keyword_directory)
  (keyword_distribute)
  (keyword_do)
  (keyword_duplicate)
  (keyword_environment)
  (keyword_escaped)
  (keyword_extension)
  (keyword_fields)
  (keyword_format)
  (keyword_handler)
  (keyword_hash)
  (keyword_ignore)
  (keyword_inpath)
  (keyword_jar)
  (keyword_jsonfile)
  (keyword_lines)
  (keyword_load)
  (keyword_location)
  (keyword_msck)
  (keyword_nothing)
  (keyword_oids)
  (keyword_orc)
  (keyword_overwrite)
  (keyword_parameter)
  (keyword_parquet)
  (keyword_partitioned)
  (keyword_partitions)
  (keyword_rcfile)
  (keyword_repair)
  (keyword_replication)
  (keyword_roles)
  (keyword_sequencefile)
  (keyword_sort)
  (keyword_sorted)
  (keyword_stored)
  (keyword_style)
  (keyword_sync)
  (keyword_tblproperties)
  (keyword_terminated)
  (keyword_textfile)
  (keyword_uncached)
  (keyword_unset)
  (keyword_use)
] @keyword

; ── spark/queries/highlights.scm ────────────────────────────────────────────

[
  (keyword_optimize)
  (keyword_zorder)
  (keyword_rewrite)
  (keyword_location)
  (keyword_bucket)
] @keyword

[
  (keyword_bin_pack)
] @type.qualifier

[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword

[
  (keyword_lazy)
  (keyword_clear)
  (keyword_uncache)
  (keyword_file)
  (keyword_files)
  (keyword_jars)
  (keyword_archive)
  (keyword_archives)
  (keyword_list)
] @keyword

[
  (keyword_views)
  (keyword_collations)
  (keyword_query)
  (keyword_path)
  (keyword_default_path)
  (keyword_system_path)
  (keyword_current_schema)
  (keyword_current_database)
] @keyword

[
  (keyword_geometry)
  (keyword_geography)
] @type.builtin

[
  (keyword_call)
  (keyword_clone)
  (keyword_compute)
  (keyword_condition)
  (keyword_deep)
  (keyword_delta)
  (keyword_diagnostics)
  (keyword_distributed)
  (keyword_field)
  (keyword_get)
  (keyword_include)
  (keyword_incremental)
  (keyword_iterate)
  (keyword_leave)
  (keyword_loop)
  (keyword_message_text)
  (keyword_metadata)
  (keyword_name)
  (keyword_noscan)
  (keyword_options)
  (keyword_ordered)
  (keyword_pivot)
  (keyword_properties)
  (keyword_purge)
  (keyword_qualify)
  (keyword_repeat)
  (keyword_resignal)
  (keyword_returned_sqlstate)
  (keyword_shallow)
  (keyword_signal)
  (keyword_source)
  (keyword_sqlstate)
  (keyword_statistics)
  (keyword_stats)
  (keyword_unpivot)
  (keyword_var)
  (keyword_variable)
  (keyword_version)
  (keyword_while)
] @keyword

[
  (keyword_elseif)
] @conditional

[
  (keyword_variant)
] @type.builtin
