#!/usr/bin/env node
/**
 * Prepares generated content for the VitePress docs site before `vitepress
 * build`/`dev` runs:
 *
 *  1. Mirrors the parser build artifacts into docs/public/artifacts/ (the
 *     VitePress replacement for the old Jekyll site's
 *     `{% for file in site.static_files %}` download loop) and writes
 *     docs/downloads.md listing them.
 *  2. Writes a stub docs/coverage.md if the real one (written by
 *     tools/coverage.py) doesn't exist yet, so `npm run docs:dev` works
 *     from a fresh clone before parsers are generated.
 *
 * Both docs/downloads.md and docs/coverage.md are gitignored; always
 * regenerated, never committed.
 */

import { existsSync, mkdirSync, rmSync, cpSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, relative } from 'path';
import { fileURLToPath } from 'url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ARTIFACTS_DIR = join(ROOT, 'docs', 'public', 'artifacts');
const DOWNLOADS_MD = join(ROOT, 'docs', 'downloads.md');
const COVERAGE_MD = join(ROOT, 'docs', 'coverage.md');

// Same source list the old .github/workflows/gh-pages.yml copied into
// docs/; the base grammar's build files and manifests. Per-dialect
// src/parser.c files are intentionally excluded: they are large generated
// C sources (hundreds of thousands of lines each across 22 dialects) that
// were never part of the published artifact set.
const ARTIFACT_SOURCES = [
  'bindings',
  'queries',
  'src',
  'binding.gyp',
  'Cargo.toml',
  'CMakeLists.txt',
  'go.mod',
  'grammar.js',
  'grammar',
  'LICENSE',
  'Makefile',
  'package.json',
  'Package.swift',
  'pyproject.toml',
  'setup.py',
  'tree-sitter.json',
];

function copyArtifacts() {
  rmSync(ARTIFACTS_DIR, { recursive: true, force: true });
  mkdirSync(ARTIFACTS_DIR, { recursive: true });

  const copied = [];
  for (const name of ARTIFACT_SOURCES) {
    const src = join(ROOT, name);
    if (!existsSync(src)) {
      console.warn(`docs-prep: skipping missing ${name} (run \`npm run generate\` first for src/)`);
      continue;
    }
    cpSync(src, join(ARTIFACTS_DIR, name), { recursive: true });
    copied.push(name);
  }
  return copied;
}

function listFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...listFiles(full));
    } else {
      out.push(full);
    }
  }
  return out;
}

function writeDownloadsPage(copiedTopLevel) {
  const files = copiedTopLevel.length ? listFiles(ARTIFACTS_DIR) : [];

  const lines = [
    '---',
    'title: Downloads',
    'editLink: false',
    '---',
    '',
    '# Downloads',
    '',
    '_Generated by `scripts/docs-prep.js` from the base grammar build artifacts on `main`. Do not edit by hand._',
    '',
  ];

  if (!files.length) {
    lines.push('No artifacts available; run `npm run generate` first.', '');
  } else {
    const byTopDir = new Map();
    for (const f of files) {
      const rel = relative(ARTIFACTS_DIR, f);
      const top = rel.split('/')[0];
      if (!byTopDir.has(top)) byTopDir.set(top, []);
      byTopDir.get(top).push(rel);
    }
    for (const [top, rels] of [...byTopDir].sort()) {
      lines.push(`## ${top}`, '');
      for (const rel of rels) {
        // Root-relative, WITHOUT the site base prefix: VitePress rewrites
        // root-relative markdown links with `base` itself at build time, so
        // adding it here would double it up (base/base/artifacts/...).
        lines.push(`- [${rel}](/artifacts/${rel})`);
      }
      lines.push('');
    }
  }

  writeFileSync(DOWNLOADS_MD, lines.join('\n'));
  console.log(`docs-prep: wrote ${relative(ROOT, DOWNLOADS_MD)} (${files.length} files)`);
}

function writeCoverageStubIfMissing() {
  if (existsSync(COVERAGE_MD)) return;
  writeFileSync(COVERAGE_MD, [
    '---',
    'title: Dialect coverage',
    'editLink: false',
    '---',
    '',
    '# Dialect coverage',
    '',
    'Not generated yet in this working copy. Run:',
    '',
    '```bash',
    'npm run generate:all',
    'pip install -r tools/requirements.txt',
    'python tools/coverage.py',
    '```',
    '',
  ].join('\n'));
  console.log(`docs-prep: wrote stub ${relative(ROOT, COVERAGE_MD)} (run tools/coverage.py for the real page)`);
}

const copied = copyArtifacts();
writeDownloadsPage(copied);
writeCoverageStubIfMissing();
