; inherits: sql

; Teradata-specific keywords
[
  (keyword_multiset)
  (keyword_fallback)
  (keyword_journal)
  (keyword_dual)
  (keyword_perm)
  (keyword_permanent)
  (keyword_spool)
  (keyword_bytes)
  (keyword_account)
  (keyword_macro)
  (keyword_top)
  (keyword_global)
  (keyword_collect)
  (keyword_summary)
  (keyword_statistics)
  (keyword_stats)
  (keyword_qualify)
  (keyword_range_n)
  (keyword_case_n)
  (keyword_unknown)
  (keyword_locking)
  (keyword_access)
  (keyword_exclusive)
  (keyword_protection)
  (keyword_log)
  (keyword_minimum)
  (keyword_maximum)
  (keyword_datablocksize)
  (keyword_mergeblockratio)
  (keyword_freespace)
  (keyword_blockcompression)
  (keyword_checksum)
  (keyword_sample)
  (keyword_format)
  (keyword_help)
  (keyword_minus)
  (keyword_preserve)
  (keyword_query_band)
  (keyword_columns)
  (keyword_compress)
  (keyword_share)
] @keyword

; EXPLAIN prefix (non-ANSI; re-added over the strict ANSI base)
[
  (keyword_explain)
  (keyword_analyze)
  (keyword_verbose)
] @keyword
